### PR TITLE
Sparkly

### PR DESCRIPTION
**Pull request by jnorthrup**
seems like we talked about coroutines a while back. 

i profiled the code and found rtree dispatching the pain.  it looks like there's fanouts doing fanouts and all of it appears procedurally inline.  this https://github.com/automenta/narchy/compare/volatile1...jnorthrup:sparkly?w=1#diff-0b920477997866ec030b26090936e4c5R218 is some coroutinecontext code with an improvable usefulness to produce an asyncronous coordinate query via the very low overheads in the coroutine compiler
(just for grins, it doesn't look like a good merge cnadidate yet)

### CODE REVIEW

**Comment by automenta** [comment]
thanks! ill check it out more carefully tomrrow.  not sure if these are based on the rtree code prior to the updates i commited within the last day or so - these remove the need for a threadlocal hack used by RTreeBeliefTable by using a sort of insertion transaction parameter object called RInsert.  

the next rtree upgrade should probably make use of this to allow Concurrent RTree to access the read/write lock so that an insert doesnt actually need to even enter write lock from read lock until the decision to actually modify the tree leaf (which wont if its a merge).  

reninds me of a possible modification to the concurrent radix tree class: a sort of prefix striping involving N individual locks bifurcating the branch(es) closest to the root would alleviate contention at the single root lock it has now.  beyond that it would be nice to somehow unify the rtree and radix tree by using some kind of protocol-driven cursor or something but that will involve a lot

you can gauge realistic performance of some of these things by running the usual demos.   ( hit 'exe' to see the displayed peak 'busy' metric.  unscientific yes but it sort of works.  the system should be collecting accurate metrics internally though. )  rtree for example is used by default via RTreeBeliefTable in each concept.  

feel free to further kotlinize stuff dont worry about breaking compatibility with the original api.  pieces like rtree are relatively self contained and would be useful modules on their  own for other projects at least.

https://www.youtube.com/watch?v=zajUPJI19ZQ Venkat Subramaniam will explore the idioms and style of prominent JVM languages, and help refactor your language portfolio.

**Comment by automenta** [comment]
see javadoc on What.java and the subclass hierarchy of How.java - imagine two morphing pie charts (actually ring charts) rotating within each other

**Comment by jnorthrup** [comment]
i think the old man bob delivers better points https://youtu.be/Q_Z_8HXt68k
and on e of these languages i forget whether kotlin or groovy drops 50% off
the microbenchmark

**Comment by jnorthrup** [comment]
>feel free to further kotlinize stuff dont worry about breaking
compatibility with the original api. pieces like rtree are relatively self
contained and would be useful modules on their own for other projects at
least.

kotlin conversion is actually slightly expensive in terms of fixups.
things i've noticed:
 * the ideal java functional api usage completely cockblocks ideal kotlin
functional constructs,.  they are similar, but not identical.
 * nullability and null returns provide an interesting elvis-based ternary
substitute, but it does not coincide with any java idioms that would be
converted.
 * inlines and coroutines would in thoery be providing the benefit that you
can only otherwise get thru ASM bytecode engineering.
 * there are mind-blowing functional api's with all of the above, bearing
no relation to any java idioms that would be converted.

but this is still shit i do on my weekends

**Comment by automenta** [comment]
i not only cant see the forest from the trees im buried under the roots.  but i can expect the gains from bytecode and language tweaking are going to be relatively negligible compared to higher level algorithmic "aerodynamics" cleverness and or modifications to the JVM itself (ex: fuzzy soft references which expose runtime priorities directly to the garbage collector internals).  also important is general code readability and comprehensibilty to optimize the mental ergonomics required for other developers.

the asynch rtree lookup you suggest is feasible, in java also, using the same type of transaction parameter object i introduced for insertion.  maybe it would be called RQuery and it would consist of the traverasl parameters and callbacks allowing it to , for example, switch between INTERSECT and CONTAIN semantics mid-traversal.  HyperIterator was meant to do somethng like this but its current design is simplified into essentially a prioritized query that lazily unfolds in a progressive scan.

**Comment by jnorthrup** [comment]
i'm too far removed in this codebase from my 1.5 understandings and afaik
nars hasn't been proven to govern its attention towards embodied priorities
of survival or god's system-present goals.

 the draw for other ecosystem players is likely to be build episodic slices
of cogitation, and competitive scoring. if that's hidden in the gui, the
draw would be to bring that forward to us plebs

**Comment by jnorthrup** [comment]
so how to reach the above?    I will presume that rtee and radixtree are
the main mechanisms.


how would these enable competitive espiodic competition?

im thinking that btrfs is a defining abstraction here - COW-based fs of
updates, each root state configuration could be launched and iterated for a
period, then snapshotted, scored, and recombined with common ancestries.
if nars is sufficiently capable of function estimation, then it's human
readability is part of the big "ethics" agenda to not only advance ai but
to nanny it.

**Comment by jnorthrup** [comment]
cow-based B*tree fs ^^

**Comment by automenta** [comment]
i think the What.java thing is supposed to be the slices youre describing.  isolated attention contexts that can be controlled in the ways its javadoc describe.  yes it is probably a key to reliable human supervision because otherwise it is like expecting a successful chemical reaction by just dumping all the ingredients into one chamber and waiting for something when in reality it needs some separate stages and each stage slightly different conditions.  hence why each What can have different parameters like time duration, capacity, etc.. 

thanks for running it overnight.  not sure what setup you used.   there does seem to be some kind of insidious slow leak but i havent tried finding it yet though it is critical.  but i dont think its the Atomic field updaters as these are instanced statically and are the recommended way of doing field-wise Atomic's via VarHandle's, without needing entire Atomic___.class's

**Comment by automenta** [comment]
examples of What's:
if it were playing N games simultaneously each game would be its own What.  especially if these are different games and not just different instances of the same Game.  then the game knowledge from one doesnt directly and freely contaminate the others.  in order to allow controlled contamination, an appropriate hypervisor/meta What would be created as their super-What.  each game might also be broken down into some sub-What's, like each sensory organ.  in the end it is just a time-slicing mechanism like any OS but "how" this differs is that How it timeslices is also timesliceable.  the interference pattern of the What and How prioritizations determining system attention.

another application of What's for contrast: imagine each unit test encapsulated as a What in one system.  allowing each unit test's success to be goaled and analyzed semi-separately but, for example the failing unit tests to be given the majority of attention.  all this encapsulated in a special continously running JUnit test runner would demonstrate some degree of self-healing.

**Pull request closed without merging**
