### PR TITLE
Sparkly

### PR DESCRIPTION
**Pull request by jnorthrup**
no conflicts! ferealz!

### CODE REVIEW

**Comment by automenta** [comment]
its going to be easier for me to continue opening an IDE in order to edit hardcoded java constant parameters than for me to understand where you're going with these changes.  im curious what you're planning next but i cant merge this one

**Comment by jnorthrup** [comment]
@automenta you said irc

**Comment by automenta** [comment]
yeah im connected but no channels u remember my username /query ?

**Comment by jnorthrup** [comment]
image

**Comment by automenta** [comment]
sseehh

**Comment by jnorthrup** [comment]
this is the same constants being enumerated at decode time in tetris launch.  

image

**Pull request merged**
